// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTD4Tj83TJe5HuZYIlxjII6Coobss7s24',
    appId: '1:1014119641458:web:1fc78810a191f3dade6deb',
    messagingSenderId: '1014119641458',
    projectId: 'z-flow-new',
    authDomain: 'z-flow-new.firebaseapp.com',
    storageBucket: 'z-flow-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1weQwghcEQUoc0UW9ZjY9YFiMjjLqKI',
    appId: '1:1014119641458:android:a1de67ea9bd6f5dfde6deb',
    messagingSenderId: '1014119641458',
    projectId: 'z-flow-new',
    storageBucket: 'z-flow-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2GoVKs1ODWfAir82YCKeLTxruGnPtKlg',
    appId: '1:1014119641458:ios:bda88601980878a6de6deb',
    messagingSenderId: '1014119641458',
    projectId: 'z-flow-new',
    storageBucket: 'z-flow-new.appspot.com',
    iosBundleId: 'com.example.zFlow',
  );
}
